M48
; DRILL file {KiCad 7.0.7} date 2024 February 23, Friday 22:46:59
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-23T22:46:59+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X95.94Y-54.646
X101.72Y-54.646
T2
X93.85Y-60.916
X103.85Y-60.916
T0
M30
